# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blogwatcher < Formula
  desc "Track blog articles and detect new posts."
  homepage "https://github.com/Hyaxia/blogwatcher"
  version "0.0.1"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/Hyaxia/blogwatcher/releases/download/v0.0.1/blogwatcher_0.0.1_linux_amd64.tar.gz"
    sha256 "65b3980fcb2c2a7fa6b74951f53804fce2b1df1f777df191f6ebbcc3bb5a6038"
    def install
      bin.install "blogwatcher"
    end
  end

  test do
    system "#{bin}/blogwatcher", "--version"
  end
end
