# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blogwatcher < Formula
  desc "Track blog articles and detect new posts."
  homepage "https://github.com/Hyaxia/blogwatcher"
  version "0.0.4"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/Hyaxia/blogwatcher/releases/download/v0.0.4/blogwatcher_0.0.4_linux_amd64.tar.gz"
    sha256 "468b33612ef75f5672aa2f5c4d7c42db4c1cd4870c26027a1ec0018a91d41df5"
    def install
      bin.install "blogwatcher"
    end
  end

  test do
    system "#{bin}/blogwatcher", "--version"
  end
end
