# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blogwatcher < Formula
  desc "Track blog articles and detect new posts."
  homepage "https://github.com/Hyaxia/blogwatcher"
  version "0.0.2"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/Hyaxia/blogwatcher/releases/download/v0.0.2/blogwatcher_0.0.2_linux_amd64.tar.gz"
    sha256 "98d7ce16b3832e144bfa3ca10c13d79aacbffc3292512408e55aa5fae89ba7e3"
    def install
      bin.install "blogwatcher"
    end
  end

  test do
    system "#{bin}/blogwatcher", "--version"
  end
end
